conference_app/conference_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('conferences/', include('conferences.urls')),
    path('events/', include('events.urls')),
]

conference_app/conferences/urls.py
from conferences.views import ConferenceListView, ConferenceDetailView
from django.urls import path

urlpatterns = [
    # visi views kurie yra ne funkcija, o klases
    # juos kvieciam su papildoma as_view
    path("", ConferenceListView.as_view()),
    path("<int:pk>/", ConferenceDetailView.as_view(), name = "conference_detail"),

]

conference_app/events/urls.py
from django.urls import path
from events.views import EventDetailView, register_visitor

urlpatterns = [
    path('<int:pk>/', EventDetailView.as_view(), name = "event_detail"),
    path('register/<int:renginio_id>/', register_visitor, name = "register_visitor"),
]

conference_app/conferences/models.py
from django.db import models

# a.Konferencija – turi datą nuo-iki, pavadinimą, [sukūrimo
# ir modifikavimo datos (auto_now, auto_now_add)]

class Conference(models.Model):
    start_date = models.DateField()
    end_date = models.DateField()
    title = models.CharField(max_length = 100)

    picture = models.ImageField(null = True)

    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)


    def __str__(self):
        return self.title

conference_app/events/models.py
from django.db import models
from conferences.models import Conference

# Create your models here.
class Event(models.Model):
    data = models.DateField()
    title = models.CharField(max_length = 100)
    visitors = models.IntegerField(default = 0)

    conference = models.ForeignKey(Conference, on_delete = models.CASCADE)

    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

conference_app/conferences/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Conference

# Create your views here.

class ConferenceListView (ListView):
    model = Conference

class ConferenceDetailView(DetailView):
    model = Conference

#Alternatyva DetailView
# def conference_detail(request, pk): #pk ateina is urls failo: path("<int:pk>")
#     conference = get_object_or_404(Conference, pk = pk)
#     return render(request, "conferences/conference_detail.html", {"object": conference})

conference_app/events/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import DetailView

from events.models import Event


# Create your views here.
class EventDetailView(DetailView):
    model = Event
    context_object_name = "renginys"

# View, kuri pasiekus prie lankytoju skaiciaus bus pridetas 1
def register_visitor(request, renginio_id):
    event = get_object_or_404(Event, id = renginio_id)
    event.visitors += 1
    event.save()
    #Automatiskai issaugos i DB
    # update events set visitors = 2 where id....
    return redirect(f"/events/{renginio_id}")

conference_app/conferences/templates/conferences/conference_detail.html
{% extends "base.html" %}

{% block "title" %}
  {{object.title}}
{% endblock %}

{% block "content" %}
  <h1>{{object.title}}</h1>

  <div>Pradzia: {{object.start_date}} </div>
  <div>Pabaiga: {{object.end_date}} </div>

  <h2>Renginiai:</h2>
  <ol>
    {% for event in object.event_set.all %}
        <li>
            <a href="{% url 'event_detail' event.id %}">
                {{ event.title }}
            </a>
            ({{ event.data }})

            {% if user.is_authenticated %}
                Dalyvauja {{ event.visitors }} žmonių
            {% endif %}
        </li>
    {% endfor %}
  </ol>
{% endblock %}

conference_app/conferences/templates/conferences/conference_list.html
{% extends "base.html" %}

{% block "title" %}
Konferenciju sarasas
{% endblock %}

{% block "content" %}
    <ol>
        {% for conference in object_list %}
        <li>
            <a href="{%url 'conference_detail' conference.id %}">{{ conference.title}}</a>
<!--ALTERNATYVA, BET GERIAU PIRMAS <a href="conferences/{{conference.id}}">{{ conference.title}}</a>-->
            ({{conference.start_date}} - {{conference.end_date}})
        </li>
        {% endfor %}
    </ol>
{% endblock %}

conference_app/events/templates/events/event_detail.html
{% extends "base.html" %}

{% block "title" %}
    Renginiai
{% endblock %}

{% block "content" %}
    <h1>Renginys: {{renginys.title}}</h1>

    <div>Pradžia: {{renginys.data}}</div>
    <div>Jau dalyvauja: {{renginys.visitors}}</div>

    <a href="/events/register/{{renginys.id}}">Užsiregistruoti</a>
    <a href="{% url 'register_visitor' renginys.id %}">Užsiregistruoti</a>

{% endblock %}

conference_app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>{% block "title" %}Konferencijos{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
      </div>
    </nav>
    <div class="container py-5">
        {% if user.is_authenticated %}
            Esate prisijungęs kaip {{user.username}}
        {% else %}
            Prisijunkite: <a href="{% url 'login' %}">Prisijunkite</a>
        {% endif %}

        {% block "content" %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>